version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 3
    reviewers:
      - "poiuztrewq1"
    labels:
      - "gem"
      - "dependencies"

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 3
    reviewers:
      - "poiuztrewq1"
    labels:
      - "yarn"
      - "dependencies"
      
