require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - '.github/**/*'

Style/GuardClause:
  Enabled: true
  MinBodyLength: 3

#disabled cops
Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
    Enabled: false

