require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - '.github/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false